<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LightsOut.Wpf</AssemblyName>
    <RootNamespace>LightsOut.Wpf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.15.6755" />
    <PackageReference Include="Microsoft.Z3" Version="4.12.2" />
  </ItemGroup>

</Project>
